# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QT_design\QT_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QColor
from PyQt5.QtWidgets import QTextEdit
from pyqtgraph import GraphicsLayoutWidget
import pyqtgraph.opengl as gl

class btn_class(QtWidgets.QPushButton):
    def __init__(self, widget, obj_name, loc_x, loc_y, w, h,group):
        super(btn_class, self).__init__(widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setGeometry(loc_x, loc_y, w , h )
        self.setFont(font)
        self.setObjectName(obj_name)
        group.addButton(self)
class radio_class(QtWidgets.QRadioButton):
    def __init__(self,widget, obj_name, loc_x, loc_y, w, h,group,id):
        self,super(radio_class, self).__init__(widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setGeometry(loc_x, loc_y, w, h)
        self.setFont(font)
        self.setObjectName(obj_name)
        group.addButton(self,id)

class label_class(QtWidgets.QLabel):
    def __init__(self, widget, obj_name, loc_x, loc_y, w, h):
        super(label_class, self).__init__(widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setGeometry(loc_x, loc_y, w, h)
        self.setFont(font)
        self.setObjectName(obj_name)

class textEdit_class(QTextEdit):
    def __init__(self, widget, obj_name, loc_x, loc_y, w, h):
        super(textEdit_class, self).__init__(widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.setGeometry(loc_x, loc_y, w, h)
        self.setFont(font)
        self.setObjectName(obj_name)

class Ui_MainWindow(object):
    def __init__(self):
        self.btn_group = QtGui.QButtonGroup()
        self.btn_group_real = QtGui.QButtonGroup()
        self.radio_btn_group = QtGui.QButtonGroup()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 800)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        path1 =470; path2=510; path3=550
        #----------widgets setup -------------------
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 60, 250, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(300, 60, 400, 400))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = gl.GLViewWidget(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(720, 60, 400, 400))
        self.graphicsView_3.setObjectName("graphicsView_3")
        model_view_x = 350
        model_view_y = 530
        self.graphicsView_xy =  pg.PlotWidget(self.centralwidget)
        self.graphicsView_xy.setRange(rect=None, xRange=[-0.1,0.1], yRange=[-0.3,-0.15], padding=None, update=True, disableAutoRange=True)
        self.graphicsView_xy.setGeometry(QtCore.QRect(model_view_x, model_view_y, 250, 250))
        self.graphicsView_xy.setObjectName("graphicsView_xy")
        self.graphicsView_xz = pg.PlotWidget(self.centralwidget)
        self.graphicsView_xz.setGeometry(QtCore.QRect(model_view_x+260, model_view_y, 250, 250))
        self.graphicsView_xz.setRange(rect=None, xRange=[-0.1,0.1], yRange=[0.1,-0.1], padding=None, update=True, disableAutoRange=True)
        self.graphicsView_xz.setObjectName("graphicsView_xz")
        self.graphicsView_xyz = gl.GLViewWidget(self.centralwidget)
        self.graphicsView_xyz.setGeometry(QtCore.QRect(model_view_x+520, model_view_y, 250, 250))
        self.graphicsView_xyz.setObjectName("graphicsView_xyz")

        # ----------label setup-----------
        self.label = label_class(self.centralwidget,"label",80, 20, 200, 30)
        self.label_2 = label_class(self.centralwidget,"label_2",430, 20, 200, 30)
        self.label_pd = label_class(self.centralwidget,"label_pd",880, 20, 200, 30)
        self.xy_label = label_class(self.centralwidget, "xy_label", model_view_x+90, model_view_y-30, 200, 30)
        self.xz_label = label_class(self.centralwidget, "xz_label", model_view_x+350,  model_view_y-30, 200, 30)
        self.xyz_label = label_class(self.centralwidget, "xyz_label",model_view_x+610,  model_view_y-30, 200, 30)
        #----------btn setup real time part-----------        start_rt = 30  # btn pos x
        start_rt = 30  # btn pos x
        high_rt = 580  # btn pos y
        self.label_realtime = label_class(self.centralwidget,"label_realtime",    start_rt, high_rt-30, 300, 30)
        self.dca1000_rtbtn = btn_class(self.centralwidget, "dca1000_rtbtn",       start_rt, high_rt, 90, 30,self.btn_group_real)
        self.sendcfg_rtbtn  = btn_class(self.centralwidget,"sendcfg_rtbtn",       start_rt+100,high_rt,90,30,self.btn_group_real)
        self.exit_rtbtn  = btn_class(self.centralwidget,"exit_rtbtn",             start_rt+200,high_rt,90,30,self.btn_group_real)

        # ----------rai/Beamforming rai / Cfar+static_rm-----------
        radio_x = 30
        radio_y = 460
        self.orgin_rai = radio_class(self.centralwidget, "orgin_rai",  radio_x,     radio_y,150,30,self.radio_btn_group,0)
        self.beam_rai =  radio_class(self.centralwidget, "beam_rai",   radio_x+100, radio_y,150,30,self.radio_btn_group,1)
        self.Cfar_rai =  radio_class(self.centralwidget, "static_rai", radio_x+235, radio_y,150,30,self.radio_btn_group,2)

        #------------static rm checkbox-----------
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.sure_static = QtWidgets.QCheckBox(self.centralwidget)
        self.sure_static.setGeometry(QtCore.QRect(30, 500, 200, 30))
        self.sure_static.setFont(font)
        #------------------------------------------------

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Real-Time Radar"))
        self.label.setText(_translate("MainWindow", "Range-Doppler Image"))
        self.label_2.setText(_translate("MainWindow", "Range-Angle Image"))
        self.label_pd.setText(_translate("MainWindow", "Point-cloud"))
        self.Cfar_rai.setText(_translate("MainWindow", "C-far"))
        self.beam_rai.setText(_translate("MainWindow", "beamforming"))
        self.orgin_rai.setText(_translate("MainWindow", "FFT-RAI"))
        self.sure_static.setText(_translate("MainWindow", "static_clutter_rm"))
        #------realtime part-------------
        self.label_realtime.setText(_translate("MainWindow", "------ Real-time Btn set ------"))
        self.dca1000_rtbtn.setText(_translate("MainWindow", "DCA1000"))
        self.sendcfg_rtbtn.setText(_translate("MainWindow", "Send Cfg"))
        self.exit_rtbtn.setText(_translate("MainWindow", "Exit"))
        self.xy_label.setText(_translate("MainWindow", "XY-Plane"))
        self.xz_label.setText(_translate("MainWindow", "XZ-Plane"))
        self.xyz_label.setText(_translate("MainWindow", "---XZY---"))
